Disable CUDA because my laptop has no CUDA
Experiments still seem to run run but a later stage fails with an error:

~/cqx/c/datastation/virtualenv/lib/python3.7/site-packages/torch/cuda/__init__.py in _lazy_init()
    170         # This function throws if there's a driver initialization error, no GPUs
    171         # are found or any other error occurs
--> 172         torch._C._cuda_init()
    173         # Some of the queued calls may reentrantly call _lazy_init();
    174         # we need to just return without initializing in that case.

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx